spring.application.name=collections-exceptions-kata

# H2 in-memory datasource
spring.datasource.url=jdbc:h2:mem:hospitaldb;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver

# Use schema.sql + data.sql (no auto-DDL)
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.h2.console.enabled=true